### ISSUE TITLE
issues with renamer

### ISSUE THREAD

**Issue by idmanager100** [ivaano/NsxLibraryManager#33]
running win 11 and cant rename anything all thr paths are correct, they are network shares

fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'qL04YyKk2KKbO0wutq01qeyjoWMCXnxvPHSQ9TKN0c0'.
      System.Exception: No contents found in the package
         at NsxLibraryManager.Core.Services.FileInfoService.GetFileInfo(String filePath, Boolean detailed) in C:\Users\Ivan\RiderProjects\NsxLibraryManager\NsxLibraryManager.Core\Services\FileInfoService.cs:line 126
         at NsxLibraryManager.Core.Services.RenamerService.GetFilesToRenameAsync(String inputPath, Boolean recursive) in C:\Users\Ivan\RiderProjects\NsxLibraryManager\NsxLibraryManager.Core\Services\RenamerService.cs:line 97
         at NsxLibraryManager.Pages.Renamer.LoadFiles() in C:\Users\Ivan\RiderProjects\NsxLibraryManager\NsxLibraryManager\Pages\Renamer.razor.cs:line 77
         at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
         at Radzen.Blazor.RadzenButton.OnClick(MouseEventArgs args)
         at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

**Comment by Lrs121** [comment]
Working on renaming my library but they are local files not network shares.
I have run into this with empty files, non-game files (eg txt files), or games that have bad content hashes.

Since it doesnt output which file it has a problem with, I have been using NSZ to verify the contents to find which game is bad. then redumping it and using the new file.

**Comment by idmanager100** [comment]
> Please provied more details.
> 
> * Operating System  unraid docker 
> * NsxLibraryManager version v0.3.1 from GitHub tag
> * File Type xci and nsp
> * Game Type all
> * Game Region us eu 
> * TitleID of file. Multiply files none work 
> * Last TitleDB update day 15.05.24
> * Is the TitleID on tinfoil.io?
Should be all new releases

**Comment by idmanager100** [comment]
Closed by error

**Comment by mizifih** [comment]
Same thing here. Looks like everything is running alright, but when I try to rename, I can't even list titles for renaming, I get the error below.

Running Windows 10, the path is a remote share, but I mapped the network. I have DLCs, Updates and Games, in various formats. 

Running the Windows .exe release.

```
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'V57Q8UzcpfonOojtb5qZNxBCzSJLfVCzIoVQJ_GjJ0c'.
      System.Exception: No contents found in the package
         at NsxLibraryManager.Core.Services.FileInfoService.GetFileInfo(String filePath, Boolean detailed) in C:\Users\Ivan\RiderProjects\NsxLibraryManager\NsxLibraryManager.Core\Services\FileInfoService.cs:line 126
         at NsxLibraryManager.Core.Services.RenamerService.GetFilesToRenameAsync(String inputPath, Boolean recursive) in C:\Users\Ivan\RiderProjects\NsxLibraryManager\NsxLibraryManager.Core\Services\RenamerService.cs:line 97
         at NsxLibraryManager.Pages.Renamer.LoadFiles() in C:\Users\Ivan\RiderProjects\NsxLibraryManager\NsxLibraryManager\Pages\Renamer.razor.cs:line 77
         at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
         at Radzen.Blazor.RadzenButton.OnClick(MouseEventArgs args)
         at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

**Comment by mizifih** [comment]
I was having the same problem, I opened a issue, but figured some stuff out.
Give this a read, if possible: [Issue nº ](https://github.com/ivaano/NsxLibraryManager/issues/37)https://github.com/ivaano/NsxLibraryManager/issues/37.

**Comment by ivaano** [comment]
there is a new beta version that has a new renamer and it improves the old one please check it out and provide any feedback [https://github.com/ivaano/NsxLibraryManager/releases/tag/v0.4.0-beta.1](url)

**Comment by ivaano** [comment]
Closing this as there is no new feedback, the new version has more checks, if a file can't be read the log should tell you what the problem is, if this happens on the new release please open a new issue.
